spring.application.name=pedido-service
server.port=8080

spring.datasource.url=jdbc:mysql://mysql:3306/pizzaria
spring.datasource.username=root
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL direta para o cliente-service no ambiente Docker
cliente-service.url=http://cliente-service:8081
